version: '3.4'
services:
  postgis: 
    image: kartoza/postgis:9.6-2.4
    ports:
      - "5432:5432"

  ubuntu:
    image: ubuntu:bionic
    entrypoint: tail -f /dev/null
    volumes:
      - .:/myscripts
